-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 21:18:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quickPoll
-- -----------------------------------------------------
-- RILEVAMENTO TEMPESTIVO DELLA QUALITÀ DELLA DIDATTICA
DROP SCHEMA IF EXISTS `quickPoll` ;

-- -----------------------------------------------------
-- Schema quickPoll
--
-- RILEVAMENTO TEMPESTIVO DELLA QUALITÀ DELLA DIDATTICA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quickPoll` DEFAULT CHARACTER SET utf8 ;
USE `quickPoll` ;

-- -----------------------------------------------------
-- Table `quickPoll`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`user_type` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`users` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_type1_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_users_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `quickPoll`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`pwds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`pwds` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`pwds` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salt` VARCHAR(8) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`user_has_pwd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`user_has_pwd` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`user_has_pwd` (
  `user_id` INT NOT NULL,
  `pwd_id` INT NOT NULL,
  `date_from` DATETIME NOT NULL,
  `date_to` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `pwd_id`),
  INDEX `fk_user_has_pwd_pwd1_idx` (`pwd_id` ASC),
  INDEX `fk_user_has_pwd_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_pwd_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickPoll`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_pwd_pwd1`
    FOREIGN KEY (`pwd_id`)
    REFERENCES `quickPoll`.`pwds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`quality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`quality` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`quality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vote` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`courses` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `date_from` DATETIME NOT NULL,
  `date_to` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`prof_has_course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`prof_has_course` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`prof_has_course` (
  `users_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  `is_lab` TINYINT(1) NOT NULL,
  `presence` INT NOT NULL,
  PRIMARY KEY (`users_id`, `courses_id`),
  INDEX `fk_users_has_courses_courses1_idx` (`courses_id` ASC),
  INDEX `fk_users_has_courses_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_courses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `quickPoll`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_courses_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `quickPoll`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`arguments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`arguments` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`arguments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arguments_courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_arguments_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `quickPoll`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`polls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`polls` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`polls` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_polls_courses1_idx` (`course_id` ASC),
  CONSTRAINT `fk_polls_courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `quickPoll`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`polls_has_arguments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`polls_has_arguments` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`polls_has_arguments` (
  `polls_id` INT NOT NULL,
  `arguments_id` INT NOT NULL,
  PRIMARY KEY (`polls_id`, `arguments_id`),
  INDEX `fk_polls_has_arguments_arguments1_idx` (`arguments_id` ASC),
  INDEX `fk_polls_has_arguments_polls1_idx` (`polls_id` ASC),
  CONSTRAINT `fk_polls_has_arguments_polls1`
    FOREIGN KEY (`polls_id`)
    REFERENCES `quickPoll`.`polls` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_polls_has_arguments_arguments1`
    FOREIGN KEY (`arguments_id`)
    REFERENCES `quickPoll`.`arguments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`votes` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`votes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `quality_id` INT NOT NULL,
  `poll_id` INT NOT NULL,
  `argument_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votes_users1_idx` (`users_id` ASC),
  INDEX `fk_votes_quality1_idx` (`quality_id` ASC),
  INDEX `fk_votes_polls_has_arguments1_idx` (`poll_id` ASC, `argument_id` ASC),
  CONSTRAINT `fk_votes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `quickPoll`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_quality1`
    FOREIGN KEY (`quality_id`)
    REFERENCES `quickPoll`.`quality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votes_polls_has_arguments1`
    FOREIGN KEY (`poll_id` , `argument_id`)
    REFERENCES `quickPoll`.`polls_has_arguments` (`polls_id` , `arguments_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`final_votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`final_votes` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`final_votes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quality_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `comment` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_final_votes_quality1_idx` (`quality_id` ASC),
  INDEX `fk_final_votes_courses1_idx` (`courses_id` ASC),
  INDEX `fk_final_votes_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_final_votes_quality1`
    FOREIGN KEY (`quality_id`)
    REFERENCES `quickPoll`.`quality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_final_votes_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `quickPoll`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_final_votes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `quickPoll`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickPoll`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quickPoll`.`comments` ;

CREATE TABLE IF NOT EXISTS `quickPoll`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `vote_id` INT NOT NULL,
  `comment` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_votes1_idx` (`vote_id` ASC),
  CONSTRAINT `fk_comments_votes1`
    FOREIGN KEY (`vote_id`)
    REFERENCES `quickPoll`.`votes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
